### ISSUE TITLE
Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by berndy2001** [vrilcode/node-red-wnsm#5]
Die Wiener Netze hatten Ende Juni ein Wartungsfenster, möglicherweise wurde da was umgestellt.
Den letzten Wert konnte erfolgreich am 2.7. nachmittags (für den Vortag) importiert werden. Seither bekomme ich diesen Fehler:

```
TypeError: Cannot read properties of null (reading '1')
    at #authenticate (./node_modules/@vrilcode/node-red-wnsm-b2b/wnsm-b2b.js:174:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WnsmB2b.call (./node_modules/@vrilcode/node-red-wnsm-b2b/wnsm-b2b.js:31:7)
```

Danke.

[L174](https://github.com/vrilcode/node-red-wnsm-b2b/blob/3a6a892194f3b455b06d6bd52bc23fc7551f4723/wnsm-b2b.js#L174C32-L174C56) ist die Ermittlung des `b2bApiKey` die anscheinend fehlschlägt.

**Comment by berndy2001** [comment]
Ping @vrilcode
