### ISSUE TITLE
Login schlägt fehl

### ISSUE THREAD

**Issue by berndy2001** [vrilcode/node-red-wnsm#6]
Wiener Netze hat wieder was umgebaut, seit einigen Tagen schlägt der Login fehl:
```
Error: Login failed - wrong credentials or application changed
    at #authenticate (/src/wnsm-b2b.js:124:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WnsmB2b.call (/src/wnsm-b2b.js:31:7)
```
Infos aus einem anderen repo: https://github.com/platysma/vienna-smartmeter/issues/178

**Comment by vrilcode** [comment]
Derzeit fehlt mir leider die Zeit diese Probleme zu untersuchen. Grundsätzlich ist die Anpassung an die künftige offizielle B2B-Schnittstelle geplant um das "moving target" sich ständig verändernder, nicht offizieller APIs zu vermeiden. Siehe auch: https://github.com/vrilcode/node-red-wnsm-b2b/discussions/1#discussioncomment-7363232 Das ist der einzige Ansatz, damit die Sache auf Dauer stabil läuft. Ich werde mir das vermutlich in ein paar Wochen ansehen.
